name: Install dependencies for OpenGL-GLUT
runs:
  using: "composite"
  steps:
    - name: Install OpenGL-GLUT deps
      shell: bash
      run: |
        if ${{ toJSON( runner.os == 'Linux' ) }}; then
          echo "::group::Install OpenGL-GLUT deps (via apt-get)"
          sudo apt-get install libxi-dev libxmu-dev
          echo "::endgroup::"
        fi
    - uses: Perl-GPU/devops/github-actions/install-dep-freeglut@main
