name: Install dependencies for pogl
runs:
  using: "composite"
  steps:
    - name: Install pogl deps (Linux)
      shell: bash
      if: runner.os == 'Linux'
      run: sudo apt-get install libx11-dev libxpm-dev libxi-dev libxmu-dev freeglut3-dev
    - name: Install pogl deps (macOS)
      shell: bash
      if: runner.os == 'macOS'
      run: brew install freeglut
