name: Install GLFW
runs:
  using: "composite"
  steps:
    - name: Install GLFW (Linux)
      shell: bash
      if: ${{ runner.os == 'Linux' }}
      run: sudo apt-get install libglfw3-dev
    - name: Install GLFW (Homebrew)
      shell: bash
      if: ${{ runner.os == 'macOS' }}
      run: brew install glfw
    - name: Install GLFW (vcpkg)
      shell: bash
      if: ${{ runner.os == 'Windows' }}
      run: |
        vcpkg install glfw3
        echo "PKG_CONFIG_PATH=C:/vcpkg/installed/x64-windows/lib/pkgconfig" >> $GITHUB_ENV
    - name: Add path (Windows)
      shell: powershell
      if: ${{ runner.os == 'Windows' }}
      run: Add-Content $env:GITHUB_PATH "C:\vcpkg\installed\x64-windows\bin"
