name: issue-notify

on:
  issues:
    types: [opened]
  issue_comment:
    types: [created]

jobs:
  notify:
    runs-on: ubuntu-latest
    continue-on-error: true
    if: ${{ always() }}
    steps:
      - uses: Perl-GPU/devops/github-actions/irc-notifications@main
        with:
          target-notifications: true
