name: Install FreeGLUT
runs:
  using: "composite"
  steps:
    - name: Install FreeGLUT
      shell: bash
      run: |
        if ${{ toJSON( runner.os == 'Linux' ) }}; then
          echo "::group::Install FreeGLUT (via apt-get)"
          sudo apt-get install freeglut3-dev
          echo "::endgroup::"
        elif ${{ toJSON( runner.os == 'macOS' ) }}; then
          echo "::group::Install FreeGLUT (via brew)"
          brew install freeglut
          echo "::endgroup::"
        fi
